language: rust
sudo: false

cache:
  - cargo

env:
  RUSTINFRA_DEPLOY_DIR: book
import:
  - rust-lang/simpleinfra:travis-configs/static-websites.yml

rust:
  - stable

before_script:
  - cargo install --vers "^0.4.5" mdbook

script:
  - mdbook build && mdbook test
