[book]
authors = ["Niko Matsakis"]
language = "en"
multilingual = false
src = "src"
title = "wg-async-foundations"

[rust]
edition = "2018"

[output.html]
site-url = "/wg-async-foundations/"

[output.html.fold]
enable = true
level = 0
